{
 "title": "Polyglot Microservices Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Orders",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "analytics_total_orders_total" }
   ]
  },
  {
   "title": "Total Revenue (R$)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "analytics_total_revenue_total" }
   ]
  },
  {
   "title": "Cancelled Orders",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "analytics_cancelled_orders_total"
    }
   ]
  },
  {
   "title": "Orders per Minute",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(analytics_total_orders_total[1m])",
     "legendFormat": "orders/min"
    }
   ]
  },
  {
   "title": "RabbitMQ Queue Depth",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=~'orders.*'}",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}