global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:5000"]
    metrics_path: /metrics

  - job_name: "analytics-service"
    static_configs:
      - targets: ["analytics-service:8000"]
    metrics_path: /metrics

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
